version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      # Mount the custom nginx config as the default site config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the built static files
      - ./nginx/statics:/usr/share/nginx/html/statics:ro
    depends_on:
      - microservice1
      - microservice2
      

  microservice1:
    build: ./microservice_1
    container_name: microservice1
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  microservice2:
    build: ./microservice_2
    container_name: microservice2
    environment:
      - PORT=5001
    ports:
      - "5001:5001"